def appVersion = ""
//def gitUrl = "https://github.com/gustavoapolinario/node-todo-frontend.git"

pipeline {
    agent any
    stages {
        stage("Checkout SCM") {   
            steps {
                git env.GIT_SOURCE_URL
            }
        }
        stage('Build') {
            agent {
                label 'nodejs'
            } 
            steps {
                script {
                    print "NPM Previx path: ${env.NPM_CACHE}"
                    print "NPM configuration: "
                    sh "npm config ls -l"
                    sh "mkdir -p node_modules"
                    sh "cp -rf ${env.NPM_CACHE} ."
                    sh "npm install"
                    sh "yes | cp -rf node_modules/* ${env.NPM_CACHE}"
                    stash name: "node_modules", includes: "node_modules/**"
                }
            }
        }
        /*
        stage('Test') {
            agent {
                label 'nodejs'
            } 
            steps {
                script {
                    unstash name: 'node_modules'
                    sh 'npm test'
                }
            }
        }
        */
        stage("Build Image") {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject("${env.PROJECT_NAME}") {
                            timeout(time:20, unit:'MINUTES') {
                                unstash name: 'node_modules'
                                sh "tar -cvf app.tar node_modules package.json src"
                                def buildSelector = openshift.selector("bc/${env.APP_NAME}-docker").startBuild("--from-archive='app.tar'")
                                //todo: throw expcetion if doesn't exist
                                buildSelector.logs("-f")        
                                def dc  = openshift.selector("dc", env.APP_NAME)
                                dc.rollout().status()
                            }
                        }
                    }
                }
            }
        }
    }
}



